import 'dart:io';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:path_provider/path_provider.dart';
import 'package:open_file/open_file.dart';

class PdfService {
  static Future<void> generateAndOpen(
      Map<String, dynamic> analysisResult) async {
    final pdf = pw.Document();

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(40),
        build: (context) => [
          // 헤더
          pw.Text('Apex Aura 분석 리포트',
              style: pw.TextStyle(
                  fontSize: 24, fontWeight: pw.FontWeight.bold)),
          pw.SizedBox(height: 20),

          // 첫인상
          _section(
            '첫인상',
            analysisResult['first_impression']?['summary']?.toString() ?? '',
          ),
          pw.SizedBox(height: 12),

          // 외모 점수 (Pro)
          if (analysisResult['appearance_score'] != null) ...[
            _section(
              '외모 점수',
              '현재: ${analysisResult['appearance_score']['score']} / 10\n'
              '최적화 시: ${analysisResult['appearance_score']['optimized_limit']}',
            ),
            pw.SizedBox(height: 12),
          ],

          // 컨설턴트 리포트
          if (analysisResult['consultant_report_full'] != null)
            _section(
              '컨설턴트 리포트',
              analysisResult['consultant_report_full']['quote']?.toString() ?? '',
            ),
          if (analysisResult['consultant_report_simple'] != null &&
              analysisResult['consultant_report_full'] == null)
            _section(
              '컨설턴트 리포트',
              analysisResult['consultant_report_simple']['quote']?.toString() ?? '',
            ),
          pw.SizedBox(height: 12),

          // 액션 카드
          _section('스타일링 가이드', ''),
          ...((analysisResult['action_cards'] as List? ?? []).map((card) {
            final c = card as Map<String, dynamic>;
            return pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                pw.Text(
                  c['category']?.toString() ?? '',
                  style: pw.TextStyle(fontWeight: pw.FontWeight.bold),
                ),
                pw.Text(c['application']?.toString() ?? ''),
                pw.SizedBox(height: 8),
              ],
            );
          })),

          // 메이크업 (Pro)
          if (analysisResult['makeup_steps'] != null) ...[
            _section('메이크업 4단계', ''),
            ...((analysisResult['makeup_steps'] as List).map((step) {
              final s = step as Map<String, dynamic>;
              return pw.Column(
                crossAxisAlignment: pw.CrossAxisAlignment.start,
                children: [
                  pw.Text(
                    '${s['step_number']}단계 ${s['step_name']}',
                    style: pw.TextStyle(fontWeight: pw.FontWeight.bold),
                  ),
                  pw.Text(s['description']?.toString() ?? ''),
                  pw.SizedBox(height: 8),
                ],
              );
            })),
          ],

          // 패션 룩 (Pro)
          if (analysisResult['fashion_looks'] != null) ...[
            _section('패션 룩', ''),
            ...((analysisResult['fashion_looks'] as List).map((look) {
              final l = look as Map<String, dynamic>;
              return pw.Column(
                crossAxisAlignment: pw.CrossAxisAlignment.start,
                children: [
                  pw.Text(
                    l['name']?.toString() ?? '',
                    style: pw.TextStyle(fontWeight: pw.FontWeight.bold),
                  ),
                  pw.Text(l['rationale']?.toString() ?? ''),
                  pw.SizedBox(height: 8),
                ],
              );
            })),
          ],

          // 푸터
          pw.SizedBox(height: 20),
          pw.Text(
            '이 리포트는 쿠팡 파트너스 활동의 일환으로 제품을 추천합니다.',
            style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey),
          ),
          pw.Text(
            'Generated by Apex Aura',
            style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey),
          ),
        ],
      ),
    );

    final dir = await getApplicationDocumentsDirectory();
    final file = File('${dir.path}/apex_aura_report.pdf');
    await file.writeAsBytes(await pdf.save());
    await OpenFile.open(file.path);
  }

  static pw.Widget _section(String title, String content) {
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        pw.Text(title,
            style: pw.TextStyle(
                fontSize: 14, fontWeight: pw.FontWeight.bold)),
        pw.SizedBox(height: 4),
        if (content.isNotEmpty)
          pw.Text(content, style: const pw.TextStyle(fontSize: 12)),
        pw.Divider(),
      ],
    );
  }
}
